Repository hassio-addons/addon-emqx, pull requests merged in 2023-03, with the labels that each got.

#27 ⬆️ Upgrades add-on base image to 6.2.3
  emqx/Dockerfile
  emqx/build.yaml
Labels: dependencies

#26 ⬆️ Upgrades EMQX to v5.0.19
  emqx/Dockerfile
Labels: dependencies

#29 ⬆️ Upgrades EMQX to v5.0.20
  emqx/Dockerfile
Labels: dependencies

#31 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  emqx/Dockerfile
Labels: maintenance

#37 Fix broken URL
  emqx/DOCS.md
Labels: documentation

#38 Limit maximum open file handles for EMQX specifically
  emqx/rootfs/etc/s6-overlay/s6-rc.d/emqx/run
Labels: enhancement
